[env:newthing]
extends = esp32c3_base, inkhud
board = esp32-c3-devkitc-02
board_level = extra
build_flags = 
  ${esp32c3_base.build_flags}
  ${inkhud.build_flags}
  -L "${platformio.libdeps_dir}/${this.__env__}/bsec2/src/cortex-m4/fpv4-sp-d16-hard"
  -D PRIVATE_HW
  -I variants/esp32c3/newthing
  -DEINK_DISPLAY_MODEL=GxEPD2_154_M09
  -DEINK_WIDTH=200
  -DEINK_HEIGHT=200
  -DINKHUD_BUILDCONF_DRIVER=ZJY200200_0154DAAMFGN
  -DINKHUD_BUILDCONF_DISPLAYRESILIENCE=15
upload_protocol = espota
build_src_filter =
  ${esp32c3_base.build_src_filter}
  ${inkhud.build_src_filter}
#board_build.filesystem = littlefs
lib_deps =
  ${esp32c3_base.lib_deps}
  ${inkhud.lib_deps}
  zinggjm/GxEPD2@^1.6.2
  lewisxhe/PCF8563_Library@^1.0.1
upload_port = "10.99.85.4"  